const BTM_MAILBOX_VERSION='0.15';
(function(){
const state={selectedId:null};
function e(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function fr(s){try{return new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(String(s)+'T12:00:00'));}catch(_){return s;}}
function activeIndex(){const id=typeof getActiveCareerId==='function'?getActiveCareerId():null;const careers=typeof loadCareers==='function'?loadCareers():[];const index=careers.findIndex(c=>c.id===id);return{careers,index,career:index>=0?careers[index]:null};}
function save(careers,index,career){career.updatedAt=new Date().toISOString();careers[index]=career;if(typeof saveCareers==='function')saveCareers(careers,{silent:true});}
function box(c){if(c)c.mailbox=Array.isArray(c.mailbox)?c.mailbox:[];}
function id(p){return p+'_'+Date.now()+'_'+Math.random().toString(16).slice(2);}
function has(c,d,t){return c.mailbox.some(m=>m.date===d&&m.type===t);}
function push(c,msg){box(c);c.mailbox.unshift({id:id('mail'),read:false,createdAt:new Date().toISOString(),...msg});}
function nextLabel(c){const m=typeof getNextCareerMatch==='function'?getNextCareerMatch(c):null;return m?(typeof getMatchLabel==='function'?getMatchLabel(m):m.homeClubName+' vs '+m.awayClubName):'Saison terminée';}
function daily(c,d){if(!c)return;box(c);if(!has(c,d,'briefing'))push(c,{date:d,type:'briefing',title:'Briefing du jour',body:'Date : '+fr(d)+'\n\nLe staff a mis à jour le carnet. Prochain rendez-vous : '+nextLabel(c)+'.'});if(!has(c,d,'news')&&Math.random()<.35)push(c,{date:d,type:'news',title:'Revue de presse',body:'La presse locale surveille la dynamique du club.'});}
function matchMail(c,r){if(!c||!r)return;box(c);const d=c.currentDate||new Date().toISOString().slice(0,10);if(has(c,d,'match-report'))return;push(c,{date:d,type:'match-report',title:'Rapport de match',body:'Résultat : '+r.homeClubName+' '+r.homeGoals+' - '+r.awayGoals+' '+r.awayClubName+'\n\nBilan : '+(r.resultForUser||'Résultat enregistré')+'.'});}
window.btmGenerateDailyMail=daily;window.btmGenerateMatchMail=function(c,r){const a=activeIndex();const career=a.career||c;if(!career)return;matchMail(career,r);if(a.index>=0)save(a.careers,a.index,career);};
window.btmGenerateTransferMail=function(c,p,price){const a=activeIndex();const career=a.career||c;if(!career||!p)return;const d=career.currentDate||new Date().toISOString().slice(0,10);push(career,{date:d,type:'transfer',title:'Transfert finalisé',body:p.name+' rejoint '+(career.club?.name||'le club')+'. Montant : '+(typeof formatMoney==='function'?formatMoney(price):price)+'.'});if(a.index>=0)save(a.careers,a.index,career);};
function ensureUi(){const nav=document.querySelector('.nav');if(nav&&!nav.querySelector('[data-screen="mail"]')){const b=document.createElement('button');b.className='nav-btn';b.dataset.screen='mail';b.textContent='Courrier';b.onclick=()=>typeof showScreen==='function'?showScreen('mail'):null;nav.insertBefore(b,nav.querySelector('[data-screen="transfers"]')||null);}const main=document.querySelector('.main-content');if(main&&!document.getElementById('mail')){const s=document.createElement('section');s.className='screen';s.id='mail';main.appendChild(s);}try{screenTitles.mail='Courrier';}catch(_){} }
function render(c=typeof getResolvedCareer==='function'?getResolvedCareer():null){ensureUi();const screen=document.getElementById('mail');if(!screen)return;if(!c){screen.innerHTML='<div class="section-header"><h3>Courrier</h3><p>Aucune carrière active.</p></div>';return;}box(c);if(!c.mailbox.length){daily(c,c.currentDate||'2025-08-01');const a=activeIndex();if(a.index>=0)save(a.careers,a.index,c);}const mails=c.mailbox.slice().sort((a,b)=>String(b.createdAt||b.date).localeCompare(String(a.createdAt||a.date)));if(!state.selectedId||!mails.some(m=>m.id===state.selectedId))state.selectedId=mails[0]?.id||null;const sel=mails.find(m=>m.id===state.selectedId)||mails[0];screen.innerHTML='<div class="section-header section-header-row"><div><p class="eyebrow">Inbox V0.15</p><h3>Courrier du manager</h3><p>Messages utiles à enrichir plus tard.</p></div><button class="secondary-btn" id="mail-mark-read">Marquer lu</button></div><div class="mail-v015"><div class="mail-v015-list">'+mails.map(m=>'<button class="mail-v015-item '+(m.read?'':'unread')+'" data-mail-id="'+e(m.id)+'"><span class="mail-v015-type">'+e(m.type)+'</span><strong>'+e(m.title)+'</strong><span>'+e(fr(m.date))+'</span></button>').join('')+'</div><article class="mail-v015-reader">'+(sel?'<span class="mail-v015-type">'+e(sel.type)+'</span><h3>'+e(sel.title)+'</h3><p class="save-meta">'+e(fr(sel.date))+'</p><div class="mail-v015-body">'+e(sel.body)+'</div>':'<div class="mail-v015-empty">Sélectionne un message.</div>')+'</article></div>';screen.querySelectorAll('[data-mail-id]').forEach(b=>b.onclick=()=>{state.selectedId=b.dataset.mailId;mark(state.selectedId,true,false);render();});document.getElementById('mail-mark-read')?.addEventListener('click',()=>{if(state.selectedId)mark(state.selectedId,true,true);});}
function mark(mid,read,refresh){const a=activeIndex();if(!a.career)return;box(a.career);const m=a.career.mailbox.find(x=>x.id===mid);if(m)m.read=read;save(a.careers,a.index,a.career);if(refresh&&typeof refreshUI==='function')refreshUI();}
const prev=typeof refreshUI==='function'?refreshUI:null;refreshUI=function refreshUIV015(){if(prev)prev();render();const f=document.querySelector('.sidebar-footer');if(f)f.textContent='V0.15 — Courrier';};document.addEventListener('DOMContentLoaded',()=>{ensureUi();render();});
})();
(function loadRoadmapModulesV0131ToV019(){
const styles=['season-v0131.css?v=0131','season-v0141.css?v=0141','season-v0151.css?v=0151','transfers-v017.css?v=017','training-v018.css?v=018','matchday-v019.css?v=0194','match-report-v0199.css?v=0199','match-report-force-v01910.css?v=01910'];
const scripts=['season-v0131.js?v=0131','season-v0141.js?v=0141','season-v0151.js?v=0151','player-db-v016.js?v=016','transfers-v017.js?v=017','training-v018.js?v=018','matchday-v019.js?v=0194','season-lock-v0198.js?v=0198','match-report-v0199.js?v=0199','match-report-force-v01910.js?v=01910'];
styles.forEach(h=>{if(document.querySelector('link[href*="'+h.split('?')[0]+'"]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href=h;document.head.appendChild(l);});
function load(i){if(i>=scripts.length){if(typeof refreshUI==='function')refreshUI();return;}const src=scripts[i];if(document.querySelector('script[src*="'+src.split('?')[0]+'"]')){load(i+1);return;}const s=document.createElement('script');s.src=src;s.async=false;s.onload=()=>load(i+1);document.body.appendChild(s);}load(0);
})();