const BTM_SEASON_FLOW_VERSION="0.14";
(function(){
const START="2025-08-01",FIRST_MATCH="2025-08-16";
function e(v){return typeof escapeHtml==="function"?escapeHtml(v):String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function iso(d){return d.toISOString().slice(0,10);}function date(s){return new Date(String(s||START)+"T12:00:00");}
function add(s,n){const d=date(s);d.setDate(d.getDate()+n);return iso(d);}function diff(a,b){return Math.round((date(b)-date(a))/86400000);}function fr(s){try{return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric"}).format(date(s));}catch(_){return s;}}
function matchDate(md){return add(FIRST_MATCH,(Number(md||1)-1)*7);}function getNext(c){if(typeof getNextCareerMatch==="function")return getNextCareerMatch(c);return null;}
function activeIndex(){const id=typeof getActiveCareerId==="function"?getActiveCareerId():null;const careers=typeof loadCareers==="function"?loadCareers():[];const index=careers.findIndex(c=>c.id===id);return{careers,index,career:index>=0?careers[index]:null};}
function save(careers,index,career){career.updatedAt=new Date().toISOString();careers[index]=career;if(typeof saveCareers==="function")saveCareers(careers,{silent:true});}
function ensure(career){if(!career)return false;let changed=false;if(!career.seasonStartDate){career.seasonStartDate=START;changed=true;}if(!career.currentDate){career.currentDate=START;changed=true;}if(!career.seasonDay){career.seasonDay=diff(START,career.currentDate)+1;changed=true;}return changed;}
function ensurePersist(){const a=activeIndex();if(!a.career)return null;if(ensure(a.career))save(a.careers,a.index,a.career);return a.career;}
function nextInfo(career){const m=getNext(career);if(!m)return{match:null,date:null,days:null,label:"Saison terminée"};const d=matchDate(m.matchday);return{match:m,date:d,days:Math.max(0,diff(career.currentDate,d)),label:(typeof getMatchLabel==="function"?getMatchLabel(m):m.homeClubName+" vs "+m.awayClubName)};}
function canPlay(career){if(!career)return{ok:false,message:"Aucune carrière active."};ensure(career);const n=nextInfo(career);if(!n.match)return{ok:false,message:"Aucun match à jouer."};if(diff(career.currentDate,n.date)>0)return{ok:false,message:"Match prévu le "+fr(n.date)+". Avance le calendrier pour jouer."};return{ok:true,message:"Match disponible."};}
window.btmCanPlayMatch=canPlay;
function recover(career){(Array.isArray(career.players)?career.players:[]).forEach(p=>{p.condition=Math.min(100,(Number(p.condition??100)||100)+2);});}
function advance(days){const a=activeIndex();if(!a.career)return;ensure(a.career);const total=Math.max(1,Number(days)||1);for(let i=0;i<total;i++){a.career.currentDate=add(a.career.currentDate,1);a.career.seasonDay=diff(START,a.career.currentDate)+1;recover(a.career);if(typeof window.btmGenerateDailyMail==="function")window.btmGenerateDailyMail(a.career,a.career.currentDate);}save(a.careers,a.index,a.career);if(typeof refreshUI==="function")refreshUI();}
function advanceToNext(){const c=ensurePersist();if(!c)return;const n=nextInfo(c);if(!n.date)return;if(n.days<=0){if(typeof refreshUI==="function")refreshUI();return;}advance(n.days);}
window.btmAdvanceSeasonDay=advance;window.btmAdvanceToNextMatch=advanceToNext;
const oldSave=typeof saveSimulatedMatch==="function"?saveSimulatedMatch:null;saveSimulatedMatch=function saveSimulatedMatchV014(){const c=ensurePersist();const gate=canPlay(c);if(!gate.ok)return{ok:false,message:gate.message};const res=oldSave?oldSave():{ok:false,message:"Simulation indisponible."};if(res&&res.ok&&typeof window.btmGenerateMatchMail==="function"){const fresh=typeof getResolvedCareer==="function"?getResolvedCareer():null;window.btmGenerateMatchMail(fresh||c,res.result||fresh?.lastMatchResult);}return res;};
function render(){const main=document.querySelector(".main-content");if(!main)return;const career=ensurePersist();let box=document.getElementById("season-v014");if(!box){box=document.createElement("div");box.id="season-v014";box.className="season-v014";const top=document.querySelector(".topbar");if(top&&top.nextSibling)main.insertBefore(box,top.nextSibling);else main.prepend(box);}if(!career){box.innerHTML="";return;}const n=nextInfo(career);const unread=(Array.isArray(career.mailbox)?career.mailbox.filter(m=>!m.read).length:0);box.innerHTML=`<div class="season-v014-left"><div class="season-v014-date"><span>Date du jour</span><strong>${e(fr(career.currentDate))}</strong></div><div class="season-v014-next"><span>Prochain match</span><strong>${e(n.label)}</strong><small>${n.date?` · ${e(fr(n.date))} · J-${n.days}`:""}</small><div class="season-v014-warning">${canPlay(career).ok?"Match disponible si la compo est prête":"Rythme jour par jour actif"}</div></div></div><div class="season-v014-actions"><button class="secondary-btn" id="season-next-day">Jour suivant</button><button class="primary-btn" id="season-next-match">Avancer au prochain match</button><button class="secondary-btn" id="season-open-mail">Courrier ${unread?`<span class='season-v014-mail-pill'>${unread}</span>`:""}</button></div>`;document.getElementById("season-next-day")?.addEventListener("click",()=>advance(1));document.getElementById("season-next-match")?.addEventListener("click",advanceToNext);document.getElementById("season-open-mail")?.addEventListener("click",()=>document.querySelector('[data-screen="mail"]')?.click());}
function decorateMatchButton(){const c=ensurePersist();const btn=document.getElementById("prematch-launch");if(!btn||!c)return;const gate=canPlay(c);if(!gate.ok){btn.disabled=true;btn.title=gate.message;}}
const prev=typeof refreshUI==="function"?refreshUI:null;refreshUI=function refreshUIV014(){if(prev)prev();render();decorateMatchButton();const f=document.querySelector(".sidebar-footer");if(f)f.textContent="V0.14 — Saison jour par jour";};document.addEventListener("DOMContentLoaded",()=>{render();decorateMatchButton();});
})();