const BTM_MAILBOX_VERSION="0.15";
(function(){
const state={selectedId:null};
function e(v){return typeof escapeHtml==="function"?escapeHtml(v):String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function fr(s){try{return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(String(s)+"T12:00:00"));}catch(_){return s;}}
function activeIndex(){const id=typeof getActiveCareerId==="function"?getActiveCareerId():null;const careers=typeof loadCareers==="function"?loadCareers():[];const index=careers.findIndex(c=>c.id===id);return{careers,index,career:index>=0?careers[index]:null};}
function save(careers,index,career){career.updatedAt=new Date().toISOString();careers[index]=career;if(typeof saveCareers==="function")saveCareers(careers,{silent:true});}
function ensureBox(career){if(!career)return;career.mailbox=Array.isArray(career.mailbox)?career.mailbox:[];}
function id(prefix){return prefix+"_"+Date.now()+"_"+Math.random().toString(16).slice(2);}
function hasMail(career,date,type){return career.mailbox.some(m=>m.date===date&&m.type===type);}
function pushMail(career,msg){ensureBox(career);career.mailbox.unshift({id:id("mail"),read:false,createdAt:new Date().toISOString(),...msg});}
function nextMatchInfo(career){const m=typeof getNextCareerMatch==="function"?getNextCareerMatch(career):null;const label=m?(typeof getMatchLabel==="function"?getMatchLabel(m):m.homeClubName+" vs "+m.awayClubName):"Saison terminée";return{match:m,label};}
function generateDaily(career,date){if(!career)return;ensureBox(career);if(!hasMail(career,date,"briefing")){const n=nextMatchInfo(career);pushMail(career,{date,type:"briefing",title:"Briefing du jour",body:`Date : ${fr(date)}\n\nLe staff a mis à jour le carnet du manager. Prochain rendez-vous : ${n.label}. Pense à surveiller la condition du groupe avant de lancer la prochaine journée.`});}
if(!hasMail(career,date,"news")&&Math.random()<.55){const lines=["La presse locale commence à évoquer la dynamique du club.","Les supporters attendent une réaction forte lors du prochain match.","Un agent a été aperçu dans les tribunes. Pour l’instant, rien d’officiel.","Les observateurs notent que le calendrier pourrait peser sur la condition du groupe."];pushMail(career,{date,type:"news",title:"Revue de presse",body:lines[Math.floor(Math.random()*lines.length)]});}}
function generateMatch(career,result){if(!career||!result)return;ensureBox(career);const date=career.currentDate||new Date().toISOString().slice(0,10);if(hasMail(career,date,"match-report"))return;const score=`${result.homeClubName} ${result.homeGoals} - ${result.awayGoals} ${result.awayClubName}`;pushMail(career,{date,type:"match-report",title:"Rapport de match",body:`Résultat : ${score}\n\nBilan : ${result.resultForUser||"Résultat enregistré"}. Le staff recommande de vérifier la condition des titulaires avant de poursuivre le calendrier.`});}
window.btmGenerateDailyMail=generateDaily;window.btmGenerateMatchMail=function(career,result){const a=activeIndex();const c=a.career||career;if(!c)return;generateMatch(c,result);if(a.index>=0)save(a.careers,a.index,c);};
window.btmGenerateTransferMail=function(career,player,price){if(!career||!player)return;const a=activeIndex();const c=a.career||career;ensureBox(c);const date=c.currentDate||new Date().toISOString().slice(0,10);pushMail(c,{date,type:"transfer",title:"Transfert finalisé",body:`${player.name} rejoint ${c.club?.name||"le club"}.\n\nMontant estimé : ${typeof formatMoney==="function"?formatMoney(price):price}. Le staff recommande de vérifier son intégration dans l’effectif et la masse salariale.`});if(a.index>=0)save(a.careers,a.index,c);};
function ensureUi(){const nav=document.querySelector(".nav");if(nav&&!nav.querySelector('[data-screen="mail"]')){const b=document.createElement("button");b.className="nav-btn";b.dataset.screen="mail";b.textContent="Courrier";b.addEventListener("click",()=>typeof showScreen==="function"?showScreen("mail"):null);nav.insertBefore(b,nav.querySelector('[data-screen="transfers"]')||null);}const main=document.querySelector(".main-content");if(main&&!document.getElementById("mail")){const section=document.createElement("section");section.className="screen";section.id="mail";section.innerHTML="<div class='section-header'><h3>Courrier</h3><p>Chargement du courrier…</p></div>";main.appendChild(section);}try{screenTitles.mail="Courrier";}catch(_){}}
function render(career=typeof getResolvedCareer==="function"?getResolvedCareer():null){ensureUi();const screen=document.getElementById("mail");if(!screen)return;if(!career){screen.innerHTML="<div class='section-header'><h3>Courrier</h3><p>Aucune carrière active.</p></div>";return;}ensureBox(career);if(!career.mailbox.length){generateDaily(career,career.currentDate||"2025-08-01");const a=activeIndex();if(a.index>=0)save(a.careers,a.index,career);}const mails=career.mailbox.slice().sort((a,b)=>String(b.createdAt||b.date).localeCompare(String(a.createdAt||a.date)));if(!state.selectedId||!mails.some(m=>m.id===state.selectedId))state.selectedId=mails[0]?.id||null;const selected=mails.find(m=>m.id===state.selectedId)||mails[0];screen.innerHTML=`<div class="section-header section-header-row"><div><p class="eyebrow">Inbox V0.15</p><h3>Courrier du manager</h3><p>Briefings quotidiens, rapports du staff et premières news dynamiques.</p></div><button class="secondary-btn" id="mail-mark-read">Marquer lu</button></div><div class="mail-v015"><div class="mail-v015-list">${mails.map(m=>`<button class="mail-v015-item ${m.read?"":"unread"}" data-mail-id="${e(m.id)}"><span class="mail-v015-type">${e(m.type)}</span><strong>${e(m.title)}</strong><span>${e(fr(m.date))}</span></button>`).join("")||"<div class='mail-v015-empty'>Aucun courrier.</div>"}</div><article class="mail-v015-reader">${selected?`<span class="mail-v015-type">${e(selected.type)}</span><h3>${e(selected.title)}</h3><p class="save-meta">${e(fr(selected.date))}</p><div class="mail-v015-body">${e(selected.body)}</div>`:"<div class='mail-v015-empty'>Sélectionne un message.</div>"}</article></div>`;screen.querySelectorAll("[data-mail-id]").forEach(btn=>btn.addEventListener("click",()=>{state.selectedId=btn.dataset.mailId;mark(state.selectedId,true,false);render();}));document.getElementById("mail-mark-read")?.addEventListener("click",()=>{if(state.selectedId)mark(state.selectedId,true,true);});}
function mark(id,read,refresh){const a=activeIndex();if(!a.career)return;ensureBox(a.career);const m=a.career.mailbox.find(x=>x.id===id);if(m)m.read=read;save(a.careers,a.index,a.career);if(refresh&&typeof refreshUI==="function")refreshUI();}
const prev=typeof refreshUI==="function"?refreshUI:null;refreshUI=function refreshUIV015(){if(prev)prev();const c=typeof getResolvedCareer==="function"?getResolvedCareer():null;ensureUi();render(c);const f=document.querySelector(".sidebar-footer");if(f)f.textContent="V0.15 — Courrier";};document.addEventListener("DOMContentLoaded",()=>{ensureUi();render();});
})();

(function loadRoadmapModulesV0131ToV018(){
const styles=["season-v0131.css?v=0131","season-v0141.css?v=0141","season-v0151.css?v=0151","transfers-v017.css?v=017","training-v018.css?v=018"];
const scripts=["season-v0131.js?v=0131","season-v0141.js?v=0141","season-v0151.js?v=0151","player-db-v016.js?v=016","transfers-v017.js?v=017","training-v018.js?v=018"];
styles.forEach(h=>{if(document.querySelector(`link[href*=\"${h.split("?")[0]}\"]`))return;const l=document.createElement("link");l.rel="stylesheet";l.href=h;document.head.appendChild(l);});
function load(i){if(i>=scripts.length){if(typeof refreshUI==="function")refreshUI();return;}const src=scripts[i];if(document.querySelector(`script[src*=\"${src.split("?")[0]}\"]`)){load(i+1);return;}const s=document.createElement("script");s.src=src;s.async=false;s.onload=()=>load(i+1);document.body.appendChild(s);}load(0);
})();