const BTM_MATCHDAY_DOSSIER_VERSION="0.13";
(function(){
function e(v){return typeof escapeHtml==="function"?escapeHtml(v):String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function s(v,f="—"){return typeof safeText==="function"?safeText(v,f):(v===undefined||v===null||v===""?f:String(v));}
function nextMatch(c){if(!c)return null;if(typeof ensureCareerCalendar==="function")ensureCareerCalendar(c);if(typeof getNextCareerMatch==="function")return getNextCareerMatch(c);return null;}
function clubById(c,id){return Array.isArray(c?.clubs)?c.clubs.find(x=>x.id===id)||null:null;}
function matchLabel(m){return m?`${m.homeClubName} vs ${m.awayClubName}`:"Saison terminée";}
function userVenue(c,m){if(!c?.club||!m)return"—";return m.homeClubId===c.club.id?"Domicile":m.awayClubId===c.club.id?"Extérieur":"—";}
function opponent(c,m){if(!c?.club||!m)return null;const id=m.homeClubId===c.club.id?m.awayClubId:m.homeClubId;return clubById(c,id);}
function level(club){const r=Number(club?.reputation)||65;if(r>=88)return"Très fort";if(r>=78)return"Fort";if(r>=68)return"Équilibré";return"Abordable";}
function lineupStats(c){return typeof prematchLineupStats==="function"?prematchLineupStats(c):{valid:false,formation:"—",rating:"—",condition:"—",starters:[],startersCount:0,expectedCount:11,warnings:["Composition non disponible."]};}
function player(c,id){return Array.isArray(c?.players)?c.players.find(p=>p.id===id)||null:null;}
function xiHtml(c,stats){const starters=Array.isArray(stats.starters)?stats.starters:[];if(!starters.length)return"<p class='save-meta'>Aucune composition enregistrée.</p>";return`<div class="match-v013-xi">${starters.map(st=>{const p=player(c,st.playerId);return`<div class="match-v013-xi-row"><b>${e(st.label||st.position)}</b><strong>${e(p?p.name:"Poste vide")}</strong><span>${e(p?p.primaryPosition:"—")} · ${s(p?.overall)}</span></div>`}).join("")}</div>`;}
function lastResultHtml(c){const r=c?.lastMatchResult;if(!r)return"";const score=`${r.homeClubName} ${r.homeGoals} - ${r.awayGoals} ${r.awayClubName}`;return`<article class="match-v013-card match-v013-last"><span class="match-v013-tag">Dernier rapport</span><h3>${e(score)}</h3><p><strong>${e(r.resultForUser||"Résultat")}</strong> · ${e(r.summary||"Résumé non disponible.")}</p></article>`;}
function bind(){const edit=document.getElementById("match-v013-edit");if(edit)edit.onclick=()=>{const b=document.querySelector('[data-screen="lineup"]');if(b)b.click();};const launch=document.getElementById("prematch-launch");if(launch&&!launch.disabled)launch.onclick=()=>{const note=document.getElementById("prematch-launch-note");const res=typeof saveSimulatedMatch==="function"?saveSimulatedMatch():{ok:false,message:"Simulation indisponible."};if(!res.ok){if(note){note.innerHTML=`<strong>Impossible :</strong> ${e(res.message)}`;note.classList.add("visible");}return;}if(typeof refreshUI==="function")refreshUI();};}
function render(c=typeof getResolvedCareer==="function"?getResolvedCareer():null){const screen=document.getElementById("match");if(!screen)return;if(!c){screen.innerHTML="<div class='section-header'><h3>Match</h3><p>Aucune carrière active.</p></div>";return;}const m=nextMatch(c);const st=lineupStats(c);if(!m){screen.innerHTML="<div class='section-header'><h3>Dossier match</h3><p>Saison terminée.</p></div>"+lastResultHtml(c);return;}const opp=opponent(c,m)||{};const gate=typeof window.btmCanPlayMatch==="function"?window.btmCanPlayMatch(c):{ok:true,message:""};const canLaunch=st.valid&&gate.ok;screen.innerHTML=`<div class="match-v013"><div class="match-v013-head"><div><span class="match-v013-tag">Dossier tactique V0.13</span><h3>${e(matchLabel(m))}</h3><p>Journée ${s(m.matchday)} · ${e(userVenue(c,m))} · Préparer, observer, décider.</p></div><div class="match-v013-actions"><button class="secondary-btn" id="match-v013-edit">Modifier la compo</button><button class="primary-btn" id="prematch-launch" ${canLaunch?"":"disabled"}>Simuler la journée</button></div></div>${lastResultHtml(c)}<div class="match-v013-board"><article class="match-v013-club"><span class="match-v013-tag">Nous</span><h2>${e(c.club?.name||"Ton club")}</h2><p>${e(level(c.club))} · ${e(userVenue(c,m))}</p></article><article class="match-v013-vs"><strong>VS</strong><span>J${s(m.matchday)}</span></article><article class="match-v013-club"><span class="match-v013-tag">Adversaire</span><h2>${e(opp.name||"Adversaire")}</h2><p>${e(level(opp))} · réputation ${s(opp.reputation)}</p></article></div><div class="match-v013-grid"><article class="match-v013-card"><h3>Notre XI</h3><div class="match-v013-kpis"><div><span>Formation</span><strong>${e(st.formation)}</strong></div><div><span>Note XI</span><strong>${s(st.rating)}</strong></div><div><span>Condition</span><strong>${s(st.condition)}%</strong></div><div><span>Titulaires</span><strong>${s(st.startersCount)}/${s(st.expectedCount)}</strong></div></div>${xiHtml(c,st)}</article><article class="match-v013-card"><h3>Décision du coach</h3><p class="match-v013-note">${st.valid?"Le onze est prêt. Vérifie la date de match avant de lancer la journée.":"La composition doit encore être sécurisée avant le match."}</p>${gate.ok?"":`<div class="match-v013-alert">${e(gate.message)}</div>`}${st.warnings?.length?`<div class="match-v013-alert">${st.warnings.slice(0,4).map(e).join("<br>")}</div>`:""}<div id="prematch-launch-note" class="prematch-launch-note"></div></article></div></div>`;bind();}
const prev=typeof refreshUI==="function"?refreshUI:null;refreshUI=function refreshUIV013(){if(prev)prev();render();};document.addEventListener("DOMContentLoaded",()=>render());
})();