const BTM_SQUAD_ENTRYPOINT_VERSION="0.22";
(function(){
const state={filter:"all",selectedId:null};
const groups={all:[],GK:["GK"],DEF:["DD","DC","DG"],MID:["MDC","MC","MOC"],ATT:["AD","AG","BU"]};
function e(v){return typeof escapeHtml==="function"?escapeHtml(v):String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function s(v,f="—"){return typeof safeText==="function"?safeText(v,f):(v===undefined||v===null||v===""?f:String(v));}
function money(v){return typeof formatMoney==="function"?formatMoney(v):s(v);}function pos(p){return typeof getPositionLabel==="function"?getPositionLabel(p):s(p);}
function sorted(c){const p=Array.isArray(c?.players)?c.players:[];return typeof sortPlayers==="function"?sortPlayers(p):p.slice();}
function visible(players){const allowed=groups[state.filter]||[];return allowed.length?players.filter(p=>allowed.includes(p.primaryPosition)):players;}
function tag(n){const c=s(n);const code=c.slice(0,3).toUpperCase();return `<span class="squad-v012-country"><span class="squad-v012-country-code">${e(code)}</span>${e(c)}</span>`;}
function filters(){return `<div class="squad-v012-filters">${[["all","Tous"],["GK","Gardiens"],["DEF","Défense"],["MID","Milieu"],["ATT","Attaque"]].map(([k,l])=>`<button class="squad-v012-filter${state.filter===k?" active":""}" data-squad-filter="${k}">${l}</button>`).join("")}</div>`;}
function row(p){const sec=Array.isArray(p.secondaryPositions)&&p.secondaryPositions.length?p.secondaryPositions.join("/"):"—";return `<button class="squad-v012-row${p.id===state.selectedId?" active":""}" data-squad-player="${e(p.id)}" type="button"><span class="squad-v012-shirt">${e(p.primaryPosition||"?")}</span><span class="squad-v012-name"><strong>${e(p.name)}</strong><span>${e(pos(p.primaryPosition))} · Sec. ${e(sec)} · ${tag(p.nationality)}</span></span><span class="squad-v012-cell"><small>OVR</small>${s(p.overall)}</span><span class="squad-v012-cell"><small>POT</small>${s(p.potential)}</span><span class="squad-v012-cond">${s(p.condition,100)}%</span></button>`;}
function dossier(p){if(!p)return `<article class="squad-v012-dossier squad-v012-empty"><h3>Dossier joueur</h3><p>Aucun joueur dans ce filtre.</p></article>`;const sec=Array.isArray(p.secondaryPositions)&&p.secondaryPositions.length?p.secondaryPositions.join(" / "):"Aucun";const bars=[["Attaque",p.attack],["Défense",p.defense],["Physique",p.physical],["Mental",p.mental]];return `<article class="squad-v012-dossier"><div class="squad-v012-big-rating">${s(p.overall)}</div><div class="squad-v012-player-top"><div class="squad-v012-silhouette" aria-hidden="true"></div><div><p class="eyebrow">Dossier joueur</p><h3>${e(p.name)}</h3><p class="squad-v012-role">${e(pos(p.primaryPosition))} · ${e(p.age)} ans · ${tag(p.nationality)}</p><div class="squad-v012-badges"><span class="squad-v012-badge">POT ${s(p.potential)}</span><span class="squad-v012-badge">${s(p.condition,100)}% condition</span><span class="squad-v012-badge">${e(p.injuryStatus||"Disponible")}</span></div></div></div><div class="squad-v012-info-grid"><div class="squad-v012-info"><span>Poste principal</span><strong>${e(p.primaryPosition)}</strong></div><div class="squad-v012-info"><span>Postes secondaires</span><strong>${e(sec)}</strong></div><div class="squad-v012-info"><span>Valeur</span><strong>${money(p.value)}</strong></div><div class="squad-v012-info"><span>Salaire</span><strong>${money(p.salary)}</strong></div><div class="squad-v012-info"><span>Contrat</span><strong>${s(p.contractYears)} an(s)</strong></div><div class="squad-v012-info"><span>Morale</span><strong>${e(p.morale||"Normal")}</strong></div></div><div class="squad-v012-bars">${bars.map(([l,v])=>`<div class="squad-v012-bar"><span>${l}</span><div class="squad-v012-bar-track"><div class="squad-v012-bar-fill" style="width:${Math.max(0,Math.min(100,Number(v)||0))}%"></div></div><strong>${s(v)}</strong></div>`).join("")}</div><div class="squad-v012-coach-note"><strong>Note coach</strong><br>Profil à surveiller selon la forme, la fatigue et les besoins tactiques du prochain match.</div></article>`;}
function render(c=typeof getResolvedCareer==="function"?getResolvedCareer():null){const container=document.getElementById("players-preview");if(!container)return;if(!c){container.innerHTML=`<div class="empty-state compact-empty"><span>👥</span><h4>Aucune carrière active</h4><p>Crée ou charge une carrière.</p></div>`;return;}const players=sorted(c);const vis=visible(players);if(!vis.some(p=>p.id===state.selectedId))state.selectedId=vis[0]?.id||players[0]?.id||null;const sel=players.find(p=>p.id===state.selectedId)||vis[0]||players[0]||null;container.innerHTML=`<div class="squad-v012"><article class="squad-v012-board"><div class="squad-v012-head"><div><p class="eyebrow">Effectif V0.22</p><h3>Liste du groupe</h3></div><div class="squad-v012-note">${e(c.club?.shortName||c.club?.name||"Club")}<br>observer · trier · décider</div></div>${filters()}<div class="squad-v012-list-head"><span></span><span>Joueur</span><span>OVR</span><span>POT</span><span>Cond.</span></div><div class="squad-v012-list">${vis.map(row).join("")||`<div class="squad-v012-empty">Aucun joueur dans ce filtre.</div>`}</div></article>${dossier(sel)}</div>`;}
window.renderPlayersPreview=render;document.addEventListener("click",ev=>{const f=ev.target.closest("[data-squad-filter]");if(f){state.filter=f.dataset.squadFilter||"all";state.selectedId=null;render();return;}const p=ev.target.closest("[data-squad-player]");if(p){state.selectedId=p.dataset.squadPlayer;render();}});const prev=typeof refreshUI==="function"?refreshUI:null;refreshUI=function refreshUISquadV022(){if(prev)prev();render();};document.addEventListener("DOMContentLoaded",()=>render());
})();