const BTM_TRAINING_VERSION="0.18";
(function(){
const groups={GK:["GK"],DEF:["DD","DC","DG"],MID:["MDC","MC","MOC"],ATT:["AD","AG","BU"]};
const labels={GK:"Gardiens",DEF:"Défense",MID:"Milieu",ATT:"Attaque"};
const focuses={balanced:"Équilibré",physical:"Physique",technical:"Technique",tactical:"Tactique",rest:"Repos"};
function e(v){return typeof escapeHtml==="function"?escapeHtml(v):String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function active(){const id=typeof getActiveCareerId==="function"?getActiveCareerId():null;const careers=typeof loadCareers==="function"?loadCareers():[];const index=careers.findIndex(c=>c.id===id);return{careers,index,career:index>=0?careers[index]:null};}
function save(a){if(a.index<0)return;a.career.updatedAt=new Date().toISOString();a.careers[a.index]=a.career;if(typeof saveCareers==="function")saveCareers(a.careers,{silent:true});}
function ensure(c){c.trainingPlan=c.trainingPlan||{GK:"balanced",DEF:"balanced",MID:"balanced",ATT:"balanced"};return c.trainingPlan;}
function pool(c,g){return (c.players||[]).filter(p=>(groups[g]||[]).includes(p.primaryPosition));}
function set(g,f){const a=active();if(!a.career)return;ensure(a.career)[g]=f;save(a);render(a.career);}
function improve(p,focus){if(focus==="rest"){p.condition=Math.min(100,(Number(p.condition)||100)+3);return;}p.condition=Math.max(55,(Number(p.condition)||100)-(focus==="physical"?3:1));if(Math.random()>.35)return;if(focus==="physical")p.physical=Math.min(99,(Number(p.physical)||60)+1);else if(focus==="technical")p.attack=Math.min(99,(Number(p.attack)||60)+1);else if(focus==="tactical")p.mental=Math.min(99,(Number(p.mental)||60)+1);else{p.attack=Math.min(99,(Number(p.attack)||60)+(Math.random()>.7?1:0));p.mental=Math.min(99,(Number(p.mental)||60)+(Math.random()>.7?1:0));}}
function applyDays(days){const a=active();if(!a.career)return;const plan=ensure(a.career);const total=Math.max(1,Number(days)||1);for(let i=0;i<total;i++){Object.keys(groups).forEach(g=>pool(a.career,g).forEach(p=>improve(p,plan[g]||"balanced")));}a.career.lastTrainingUpdate=new Date().toISOString();save(a);}
function render(c=typeof getResolvedCareer==="function"?getResolvedCareer():null){const screen=document.getElementById("training");if(!screen)return;if(!c){screen.innerHTML="<div class='section-header'><h3>Entraînement</h3><p>Aucune carrière active.</p></div>";return;}const plan=ensure(c);screen.innerHTML=`<div class="section-header"><p class="eyebrow">Entraînement V0.18</p><h3>Plan de la semaine</h3><p>Choisis un focus par groupe. Les effets s’appliquent quand les jours avancent.</p></div><div class="training-v018">${Object.keys(groups).map(g=>{const players=pool(c,g);const avg=players.length?Math.round(players.reduce((t,p)=>t+(Number(p.condition)||100),0)/players.length):0;return`<article class="training-v018-card"><p class="eyebrow">${e(g)}</p><h3>${e(labels[g])}</h3><p>${players.length} joueur(s) · condition moyenne ${avg}%</p><div class="training-v018-focus">${Object.entries(focuses).map(([k,l])=>`<button data-training-group="${g}" data-training-focus="${k}" class="${plan[g]===k?"active":""}">${e(l)}</button>`).join("")}</div><div class="training-v018-note">Focus actuel : ${e(focuses[plan[g]]||"Équilibré")}</div></article>`}).join("")}</div>`;screen.querySelectorAll("[data-training-group]").forEach(b=>b.addEventListener("click",()=>set(b.dataset.trainingGroup,b.dataset.trainingFocus)));}
const oldAdvance=window.btmAdvanceSeasonDay;window.btmAdvanceSeasonDay=function trainingAdvanceWrapper(days){if(oldAdvance)oldAdvance(days);applyDays(days);if(typeof refreshUI==="function")refreshUI();};
window.btmApplyTrainingDays=applyDays;const prev=typeof refreshUI==="function"?refreshUI:null;refreshUI=function refreshUITrainingV018(){if(prev)prev();render();};document.addEventListener("DOMContentLoaded",()=>render());
})();